[project]
name = "complete-python-3-bootcamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ilya Popov", email = "ilypopv@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
complete-python-3-bootcamp = "complete_python_3_bootcamp:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
